add mypy typechecking to build

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -9,31 +9,40 @@ jobs:
       fail-fast: false
       matrix:
         include:
-          - python-version: "3.14"
+          - name: linux-3.14-typecheck
+            python-version: "3.14"
             args: --run-slow
             os: ubuntu-latest
-          - python-version: "3.14"
+          - name: windows-3.14
+            python-version: "3.14"
             os: windows-latest
             args: --run-slow
-          - python-version: "3.14"
+          - name: macos-3.14
+            python-version: "3.14"
             args: --run-slow
             os: macos-latest
-          - python-version: "3.13"
+          - name: linux-3.13
+            python-version: "3.13"
             args: ""
             os: ubuntu-latest
-          - python-version: "3.12"
+          - name: linux-3.12
+            python-version: "3.12"
             args: ""
             os: ubuntu-latest
-          - python-version: "3.11"
+          - name: linux-3.11
+            python-version: "3.11"
             args: ""
             os: ubuntu-latest
-          - python-version: "3.10"
+          - name: linux-3.10
+            python-version: "3.10"
             args: ""
             os: ubuntu-latest
-          - python-version: pypy-3.11
+          - name: linux-pypy-3.11
+            python-version: pypy-3.11
             args: ""
             os: ubuntu-latest
-          - python-version: pypy-3.10
+          - name: linux-pypy-3.10
+            python-version: pypy-3.10
             args: ""
             os: ubuntu-latest
     steps:
@@ -48,11 +57,20 @@ jobs:
           echo "::group::Run python -m pip install --upgrade pip setuptools wheel"
           python -m pip install --upgrade pip setuptools wheel
           echo "::endgroup::"
-          echo "::group::Run pip install -e .[test]"
-          pip install -e .[test]
+          echo "::group::Run pip install -e .[test] mypy"
+          pip install -e .[test] mypy
           echo "::endgroup::"
       - name: Run tests with ${{ matrix.args }}
         run: python run-tests.py ${{ matrix.args }}
+      - name: Run mypy (if -typecheck)
+        if: ${{ contains(matrix.name, '-typecheck') }}
+        run: |
+          echo "::group::Run mypy"
+          FAILED=0
+          python -m mypy || FAILED=$?
+          echo "::endgroup::"
+          [ $FAILED -eq 0 ] || echo "::warning::mypy failed with exit code $FAILED"
+        shell: bash
       - name: Upload test coverage
         uses: codecov/codecov-action@v4
         env:
